export const INSTRUCTOR_LIST_REQUEST = "INSTRUCTOR_LIST_REQUEST";
export const INSTRUCTOR_LIST_SUCCESS = "INSTRUCTOR_LIST_SUCCESS";
export const INSTRUCTOR_LIST_FAIL = "INSTRUCTOR_LIST_FAIL";

export const INSTRUCTOR_DETAIL_REQUEST = "INSTRUCTOR_DETAIL_REQUEST";
export const INSTRUCTOR_DETAIL_SUCCESS = "INSTRUCTOR_DETAIL_SUCCESS";
export const INSTRUCTOR_DETAIL_FAIL = "INSTRUCTOR_DETAIL_FAIL";

export const INSTRUCTOR_CREATE_REQUEST = "INSTRUCTOR_CREATE_REQUEST";
export const INSTRUCTOR_CREATE_SUCCESS = "INSTRUCTOR_CREATE_SUCCESS";
export const INSTRUCTOR_CREATE_FAIL = "INSTRUCTOR_CREATE_FAIL";

export const INSTRUCTOR_UPDATE_REQUEST = "INSTRUCTOR_UPDATE_REQUEST";
export const INSTRUCTOR_UPDATE_SUCCESS = "INSTRUCTOR_UPDATE_SUCCESS";
export const INSTRUCTOR_UPDATE_FAIL = "INSTRUCTOR_UPDATE_FAIL";

export const INSTRUCTOR_DELETE_REQUEST = "INSTRUCTOR_DELETE_REQUEST";
export const INSTRUCTOR_DELETE_SUCCESS = "INSTRUCTOR_DELETE_SUCCESS";
export const INSTRUCTOR_DELETE_FAIL = "INSTRUCTOR_DELETE_FAIL";
