export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_RELOAD = "USER_RELOAD";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const USER_COURSES_REQUEST = "USER_COURSES_REQUEST";
export const USER_COURSES_SUCCESS = "USER_COURSES_SUCCESS";
export const USER_COURSES_FAIL = "USER_COURSES_FAIL";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_ADD_COURSE_REQUEST = "USER_ADD_COURSE_REQUEST";
export const USER_ADD_COURSE_SUCCESS = "USER_ADD_COURSE_SUCCESS";
export const USER_ADD_COURSE_FAIL = "USER_ADD_COURSE_FAIL";

export const AVATAR_CHANGE_REQUEST = "AVATAR_CHANGE_REQUEST";
export const AVATAR_CHANGE_SUCCESS = "AVATAR_CHANGE_SUCCESS";
export const AVATAR_CHANGE_FAIL = "AVATAR_CHANGE_FAIL";

export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL";
